{
    "name": "Factory CRM Follow-up",
    "version": "19.5.1.3.1",
    "category": "Sales/CRM",
    "summary": "Customer grading, traceable follow-ups and factory sales reminders",
    "author": "Kasumi",
    "depends": ["crm", "auth_signup"],
    "data": [
        "security/ir.access.csv",
        "data/crm_stage_data.xml",
        "data/ir_cron_data.xml",
        "data/no_email_user_management_data.xml",
        "views/factory_crm_followup_views.xml",
        "views/res_users_views.xml",
        "views/res_partner_views.xml",
        "views/crm_lead_views.xml",
    ],
    "application": False,
    "installable": True,
    "license": "LGPL-3",
}
